modLoader="kotlinforforge"
loaderVersion="[4,)"
license='MIT'
displayURL='${source}'

[[mods]]
modId="$id"
version="$version"
displayName="$name"
authors="$author"
description='''
$description
'''

[[dependencies.${id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
