modLoader="kotlinforforge"
loaderVersion="[4,)"
license='MIT'
displayURL='${source}'

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${author}"
description='''
${description}
'''

[[dependencies.${id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
